---
abstract: 'Release tests for checking changes'
author:
  - 'Marcel Grünauer <marcel@cpan.org>'
  - 'Mike Doherty <doherty@cpan.org>'
build_requires:
  File::Find: 0
  File::Path: 0
  File::Temp: 0
  Module::Build: 0.3601
  Moose::Autobox: 0
  Test::DZil: 0
  Test::More: 0.96
  Test::Output: 0
  autodie: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300012, CPAN::Meta::Converter version 2.120900'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-Test-CheckChanges
no_index:
  directory:
    - corpus
requires:
  Dist::Zilla::Plugin::InlineFiles: 0
  Moose: 0
  Test::CheckChanges: 0
  namespace::autoclean: 0
  perl: 5.008
  strict: 0
  version: 0.77
  warnings: 0
resources:
  bugtracker: https://github.com/doherty/Dist-Zilla-Plugin-Test-CheckChanges/issues
  homepage: http://metacpan.org/release/Dist-Zilla-Plugin-Test-CheckChanges/
  repository: git://github.com/doherty/Dist-Zilla-Plugin-Test-CheckChanges.git
version: 2.000001
